stages:
  - build
  - tests
  - code_quality
  - deploy

build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm install -g @angular/cli
    - ng build
  cache:
    paths:
      - ./node_modules
  artifacts:
    expire_in: 1 hour
    paths:
      - ./dist/hello-world
  only:
    - master

tests:
  stage: tests
  image: circleci/node:14-browsers
  script:
    - sudo npm install
    - sudo npm install -g @angular/cli
    - ng test --no-watch --no-progress
  cache:
    paths:
      - ./node_modules
  only:
    - master

code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
  only:
    - master

deploy:
  stage: deploy
  image: ruby:2.7
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY --skip_cleanup=true
  only:
    - master
